// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_zm275.Models;

namespace Mission6_zm275.Migrations
{
    [DbContext(typeof(FilmApplication))]
    partial class FilmApplicationModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_zm275.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "None"
                        });
                });

            modelBuilder.Entity("Mission6_zm275.Models.FormModel", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            CategoryId = 1,
                            Director = "dave",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Fast n Furious",
                            Year = 2001
                        },
                        new
                        {
                            FormId = 3,
                            CategoryId = 1,
                            Director = "dave",
                            Edited = true,
                            Rating = "PG-13",
                            Title = "Fast N Furious 2",
                            Year = 2004
                        },
                        new
                        {
                            FormId = 2,
                            CategoryId = 2,
                            Director = "adam",
                            Edited = true,
                            LentTo = "noone",
                            Rating = "G",
                            Title = "romeo",
                            Year = 21
                        });
                });

            modelBuilder.Entity("Mission6_zm275.Models.FormModel", b =>
                {
                    b.HasOne("Mission6_zm275.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
